=== ingumsky/rex-format/rex-cli/convert/winner/xsd/foreign_commercial.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="foreign_commercial">
	<xs:complexType>
	<xs:sequence>  

	<xs:element name="obj" minOccurs="1" maxOccurs="unbounded">	
	<xs:complexType>
	  <xs:sequence>

		<xs:element name="id" type="xs:string">
			<xs:annotation>
				<xs:documentation>Уникальный идентификатор объекта. Для одного и того же объекта значение данного элемента не должно изменяться.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="date">
			<xs:annotation>
				<xs:documentation>Дата обновления состояния объекта, в формате 'DD.MM.YYYY', например: 12.02.2013</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9]{2}.[0-9]{2}.[0-9]{4}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="actual">
			<xs:annotation>
				<xs:documentation>Актуальность объявления</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="продается/арендуется"/>
					<xs:enumeration value="аванс/задаток"/>
					<xs:enumeration value="продана/арендована"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="obtp">
			<xs:annotation>
				<xs:documentation>Тип объекта.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Офис"/>
					<xs:enumeration value="Магазин"/>
					<xs:enumeration value="Склад"/>
					<xs:enumeration value="Гостиница"/>
					<xs:enumeration value="Отель"/>
					<xs:enumeration value="Предприятие питания"/>
					<xs:enumeration value="Производственно-промышленное помещение"/>
					<xs:enumeration value="Ферма"/>
					<xs:enumeration value="Земельный участок"/>
					<xs:enumeration value="Иное"/>
					<xs:enumeration value="ОСЗ"/>
					<xs:enumeration value="Кафе/Ресторан"/>
					<xs:enumeration value="Готовый бизнес"/>
					<xs:enumeration value="Бизнес-проект"/>
					<xs:enumeration value="Доходный дом"/>
					<xs:enumeration value="Фабрика/Завод"/>
					<xs:enumeration value="Инвестиционный проект"/>
					<xs:enumeration value="Курортный комплекс"/>
					<xs:enumeration value="Сельхозугодья"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="optp">
			<xs:annotation>
				<xs:documentation>Тип операции</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="аренда"/>
					<xs:enumeration value="продажа"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="land" type="xs:string">
			<xs:annotation>
				<xs:documentation>Страна.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="state" type="xs:string">
			<xs:annotation>
				<xs:documentation>Штат, область.</xs:documentation>
			</xs:annotation>
		</xs:element>	

		<xs:element name="field" type="xs:string">
			<xs:annotation>
				<xs:documentation>Район.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="town" type="xs:string">
			<xs:annotation>
				<xs:documentation>Населенный пункт.</xs:documentation>
			</xs:annotation>
		</xs:element>
		
		<xs:element name="address" type="xs:string" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Улица.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="dom" type="xs:string" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Номер дома, корпуса.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="location" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Расположение.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="у моря"/>
					<xs:enumeration value="в лесу"/>
					<xs:enumeration value="в горах"/>
					<xs:enumeration value="в большом городе"/>
					<xs:enumeration value="в пригороде"/>
					<xs:enumeration value="в деревне"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="price" type="xs:integer"> 
			<xs:annotation>
				<xs:documentation>Стоимость объекта. В значении данного элемента указывается числовое значение стоимости объекта.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="currency"> 
			<xs:annotation>
				<xs:documentation>Тип валюты, в которой указана стоимость объекта</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="RUB"/>
					<xs:enumeration value="USD"/>
					<xs:enumeration value="EUR"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="pl">
			<xs:annotation>
				<xs:documentation>Площадь строения в кв.м. Данный элемент обязателен для всех типов объектов, кроме "Земельный участок"</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:minInclusive value="5"/> 
					<xs:maxInclusive value="214000000"/> 
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="pl_s" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Площадь участка. Данный элемент обязателен только если тип объекта "Земельный участок"</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:minInclusive value="1"/> 
					<xs:maxInclusive value="16700000"/> 
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="floor" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Этаж, на котором расположен объект.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="127"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="fl_ob" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Этажность строения, в котором расположен объект.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="127"/> 
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="telefon">
			<xs:annotation>
				<xs:documentation>Контактный номер телефона в международном формате:  +[код страны][код города/оператора][номер абонента].
				В списке значения разделяются символом ";".</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="\+\d{11,18}(;\+\d{11,18})*"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="email" type="xs:string" minOccurs="0">
			<xs:annotation>
				<xs:documentation>E-mail для контактов. В списке значения разделяются символом ";"</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="company_url" type="xs:anyURI" minOccurs="0">
			<xs:annotation>
				<xs:documentation>URL сайта агентства</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="object_url" type="xs:anyURI" minOccurs="0">
			<xs:annotation>
				<xs:documentation>URL карточки объекта на сайте агентства.</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="photos" type="xs:anyURI" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Список URL фотографий объекта. В списке значения разделяются символом ";"</xs:documentation>
			</xs:annotation>
		</xs:element>

		<xs:element name="remark" minOccurs="0">
			<xs:annotation>
				<xs:documentation>Дополнительная информация об объекте. Значение данного элемента необходимо указывать в секции <![CDATA[...]]></xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="10000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element> 

	  </xs:sequence>
	</xs:complexType>
	</xs:element>
	</xs:sequence>
	</xs:complexType>

		<xs:key name="uniqueID">
			<xs:selector xpath="obj"/>
			<xs:field    xpath="id"/>
		</xs:key>

</xs:element>
</xs:schema>

=== ingumsky/rex-format/rex-cli/convert/winner/examples/foreign_commercial.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Формат WinNER-XML предназначается для описания объектов рынка недвижимости в разделе 
"Продажа и аренда коммерческой недвижимости за рубежом".


Общие замечания по формату.

WinNER-XML основан на стандарте XML (http://www.w3.org/XML), т.е. на WinNER-XML накладываются все требования 
и ограничения формата XML.


Требования к фиду.
	
1. В фиде должна передаваться актуальная информация об объектах и изменении их состояния.
2. Объявления, поступающие в Базу WinNER, должны обновляться, а не удаляться и создаваться заново.
3. В данных не допускается присутствие HTML-тегов.


Описание элементов формата WinNER-XML.

Замечание: 
- знаком "!" отмечены обязательные элементы;
- значения из перечня допустимых вариантов берутся без обрамляющих кавычек и указываются в WinNER-XML по правилам заполнения XML.

	
! <id> 

Уникальный идентификатор объекта. Для одного и того же объекта значение данного элемента не должно изменяться.


! <date>  

Дата обновления состояния объекта, в формате 'DD.MM.YYYY', например: 12.02.2013.


! <actual>

Актуальность объявления.

Допустимые варианты:
"продается/арендуется"
"аванс/задаток"
"продана/арендована"


! <obtp> 

Тип объекта.

Допустимые варианты:
"Офис"
"Магазин" 
"Склад"
"Гостиница" 
"Отель"
"Предприятие питания"
"Производственно-промышленное помещение" 
"Ферма"
"Земельный участок" 
"Иное"
"Кафе/Ресторан"
"Готовый бизнес" 
"Бизнес-проект" 
"Доходный дом"
"Фабрика/Завод"
"Инвестиционный проект" 
"Курортный комплекс"
"Сельхозугодья"


! <optp> 

Тип операции.

Допустимые варианты:
"аренда"
"продажа" 

	
! <land> 

Страна. 
	

! <state> 

Штат, область. 
	

! <field> 

Район. 

	
! <town> 

Населенный пункт. 

	
<address> 

Улица.


<dom> 

Номер дома, корпуса.
	

<location> 

Расположение.

Допустимые варианты:
"у моря"
"в лесу"
"в горах"
"в большом городе"
"в пригороде"
"в деревне"


! <price> 

Стоимость объекта.
В значении данного элемента указывается числовое значение стоимости объекта.


! <currency> 

Валюта, в которой указана смоимость. 

Допустимые варианты:
"RUB" - российские рубли
"USD" - доллары США
"EUR" - евро


! <pl> 

Площадь строения в кв.м. 
Данный элемент обязателен для всех типов объектов, кроме "Земельный участок"

	
! <pl_s> 

Площадь участка.
Данный элемент обязателен только если тип объекта "Земельный участок"


<floor> 

Этаж, на котором расположен объект.


<fl_ob>

Этажность строения, в котором расположен объект.


! <telefon>

Контактный номер телефона в международном формате:  +[код страны][код города/оператора][номер абонента].
Например, +79261234567.
В списке значения разделяются символом ";".


<email>

e-mail для контактов. В списке значения разделяются символом ";".


<company_url>

URL сайта агентства.


<object_url>

URL карточки объекта на сайте агентства.


<photos>

Список URL фотографий объекта. В списке значения разделяются символом ";".


<remark>

Дополнительная информация об объекте. Значение данного элемента необходимо указывать в секции <![CDATA[...]]>.

-->


<foreign_commercial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="foreign_commercial.xsd">
	<obj>
		<id>123</id>
		<date>01.04.2014</date>
		<actual>продается/арендуется</actual>
		<obtp>Кафе/Ресторан</obtp>
		<optp>продажа</optp>
		<land>Черногория</land>
		<state>Opstina Budva</state>
		<field>Budva</field>
		<town>Budva</town>
		<address>Маинский путь</address>
		<dom>24</dom>
		<location>у моря</location>
		<price>100000</price>
		<currency>USD</currency>
		<pl>100</pl>
		<floor>1</floor>
		<fl_ob>1</fl_ob>
		<telefon>+79261234567;+35956878008</telefon>
		<email>test@mail.ru</email>
		<company_url>http://host.com</company_url>
		<object_url>http://host.com/objects/123.html</object_url>
		<photos>http://host/image_1.jpg;http://host/image_2.jpg</photos>
		<remark><![CDATA[ресторан на 45 мест и на террасе 35 мест, офис, склад холодильник, подвал, сделан ремонт]]></remark>
	</obj>
</foreign_commercial>
